on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10

      - name: Install dependencies in the CI environ
        run: make ci-dependencies

      - name: Lint
        run: make lint

      - name: Run sonar cloud analysis
        run: echo "ok"

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10

      - name: Install dependencies in the CI environ
        run: make ci-dependencies

      - name: Test and coverage
        run: make test-coverage
